# Generated by Django 5.0.6 on 2024-06-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_id_alter_orderproduct_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Confirmed', 'Order Confirmed'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='Order Received', max_length=20),
        ),
    ]
